### ISSUE TITLE
Etsy.com not working

### ISSUE THREAD

**Issue by maxcook** [roysix/infy-scroll#12] opened 2021-07-21 07:16 UTC
search results on etsy.com are not working. It seems as if the elements are loaded but then they are put into an invisible container :(

**Comment by roysix** [comment] 2021-07-22 08:42
Hi Maximilian. Thanks for opening this issue and for using Infy.

I'm not all that familiar with the Etsy website, but upon a cursory glance, it looks like it's a Database URL that no longer works anymore because Etsy redesigned their Search Results page to be similar to [SPA (Single Page Application)](https://developer.mozilla.org/en-US/docs/Glossary/SPA) in nature. Unfortunately, SPAs are among the most complex sites to deal with, and Infy (as well as most AutoPagerize extensions) generally don't work well with them.

Luckily (for now at least), you can still make Infy work with this site by utilizing Iframes, though you'll want to open the links in a new tab. Here's two ways (which I tested using this [Example URL](https://www.etsy.com/search?q=brownies)):

1. Change the Append Mode to `Iframe`. This will append each full page in an iframe.
2. Or keep using the `Element` Append Mode, check the `Element Iframe` Checkbox and adjust the `Page Element Rule` with the following `Selector`: `div[data-behat-search-results-lg]` (or you could also use its parent div: `div[data-search-results]`

In both cases, you'll want to set the Iframe `Height Wait` (in the Iframe Append Mode settings) to something greater than 0 (like `3000` ms) in case content on the bottom of the pages appears cropped.

I'll try and update the [Help Guide](https://github.com/roysix/infy-scroll/wiki/Help) to add a section about dealing with complex sites like Etsy so users can try to figure out these settings on their own.

I'll go ahead and close this issue because it's only about a specific website that you needed settings for, and Infy seems to be working as intended.

Hope that helps and thanks again for using Infy!

**Closed by roysix** 2021-07-22 08:42 UTC

**Comment by maxcook** [comment] 2021-07-22 15:16
Thanks for the detailed help!!!

The second method works perfect. However i have an issue with the changes not beeing saved. I put in the page element rule and click the "Accept" button. It works then until i refresh the page. After refresh the original data is set again.

**Comment by roysix** [comment] 2021-07-22 21:38
Hi again Maximilian! You'll need to [Save the URL](https://github.com/roysix/infy-scroll/wiki/Help#saving-urls), which is covered in the Help Guide. Also, you'll probably want to make the Saved URL pattern have `/search` in it if this is only intended for that specific Search Results URL pattern so Infy only activates on that page and not elsewhere on the site.
